### ISSUE TITLE
binary sequence error occurs when trying to read JUNO(JADE) data

### ISSUE THREAD

**Issue by AlimyBreak** [MillionConcepts/pdr#43]
As I konw, the JADE (EDRs and RDRs)  datasets have been Officially Supported.
When I try to read the JADE files with PDR(v0.7.3), the binary data seem error sequenced.

Test code:
import pdr
data = pdr.read(r'C:\Users\Administrator\Desktop\PythonCode\JAD_L30_LRS_ELC_ANY_CNT_2022001_V04.lbl')
data.load("all")
print(data.keys())
TABLE = data["TABLE"]
print(TABLE.keys())
print(TABLE["DIM0_UTC"])
print(TABLE["DATA_UNITS"])

Error information:
![Untitled](https://user-images.githubusercontent.com/46748901/223009950-19c6b4b7-611a-449c-863c-e9c2bf722fab.png)

Ref1 is the test data link;
Ref2 provides a python method,that can read JADE binary data with no sequenced error, in its Answer part.
May be useful.

Refs:
1. https://pds-ppi.igpp.ucla.edu/data/JNO-J_SW-JAD-3-CALIBRATED-V1.0/DATA/2022/2022001/ELECTRONS/
2. https://stackoverflow.com/questions/66686265/importing-dat-files-in-python-without-knowing-how-it-is-structured

**Comment by m-stclair** [comment]
Thank you for the bug report!

The data providers have updated these products from version 3 to version 4 since we added support for them. The version 4 labels are very different and somewhat unusual, which resulted in this error. We have fixed this issue in b16094a. We will include this fix in the next `pdr` release, and if you have an urgent need to use these products in the meantime, you can clone the `develop` branch. 

(Will close this issue on next release.)

**Comment by Sierra-MC** [comment]
A new pdr version has been released (v0.7.4) that supports this data and can be used with a conda-forge or pip install. 

Thank you for your contribution to this work by making us aware of the issue!
