### ISSUE TITLE
Cannot open SPREADSHEET data object (Unable to load SPREADSHEET: 'START_BYTE')

### ISSUE THREAD

**Issue by msbentley** [MillionConcepts/pdr#45]
I have recently tried to open data products using the SPREADSHEET object (i.e. delimited ASCII tables) but get the error:
```
UserWarning: Unable to load SPREADSHEET: 'START_BYTE'
```
As far as I can see from the standard, START_BYTE should not be required here, but I could be wrong! An example product:

http://archives.esac.esa.int/psa/ftp/MARS-EXPRESS/ASPERA-3/MEX-M-ASPERA3-2-EDR-IMA-EXT7-V1.0/DATA/IMA_EDR_L1B_2019_01/IMA_AZ0020190011529C_ACCS01.CSV

http://archives.esac.esa.int/psa/ftp/MARS-EXPRESS/ASPERA-3/MEX-M-ASPERA3-2-EDR-IMA-EXT7-V1.0/DATA/IMA_EDR_L1B_2019_01/IMA_AZ0020190011529C_ACCS01.LBL

Thanks!

**Comment by m-stclair** [comment]
The error is somewhat misleading. `pdr` first attempts to read this as a delimiter-separated file (ignoring specified field widths, etc.). However, it fails, because the file contains lines with both 102 and 103 delimited fields (the "SENSOR" lines have 102, the "MODE DATA" lines have 103). After failing, it attempts to parse it using the specified field widths -- typically ASCII files _intended_ to be read this way (because they have weird padding or something) specify START_BYTE. It wouldn't _actually_ work even if START_BYTE were present, though, because of the inconsistency in the lines. Typically we handle this kind of thing by investigating the data set, seeing if the variable line lengths were a "consistent inconsistency" in this product type, and coding a special case. Do you happen to know if this is an intended/pervasive feature of these data products?

**Comment by msbentley** [comment]
Aha, thanks for digging into that - I'll try to check if there is a good reason for the inconsistency and see if we can even get it fixed in later versions (since this is for an ongoing mission).

**Comment by m-stclair** [comment]
Copy that! Thank you for the bug report. Closing this issue for now -- feel free to comment if you find information that is actionable for us, and I will reopen the issue.
