### ISSUE TITLE
Fail to load CRISM DDR data

### ISSUE THREAD

**Issue by justinbl** [MillionConcepts/pdr#54]
I try to use PDR to load CRISM DDR Data. It seems the read_pvl function cannot work. Here is the erro info
<img width="1113" alt="image" src="https://github.com/MillionConcepts/pdr/assets/19316767/ab743eb5-1928-46fe-9c29-1f5114b1c263">

Here is the link for downloading CRISM DDR data for your reference: https://pds-geosciences.wustl.edu/mro/mro-m-crism-6-ddr-v1/mrocr_1002/ddr/2009/2009_118/hrl00012522/hrl00012522_07_de183l_ddr1.img

**Comment by Sierra-MC** [comment]
Hi @justinbl,

With a bit of testing I was able to reproduce your error. It appears you do not have the label file in the same directory as the data file. While you can pass either the data file (the .img you've linked here) or the label file (same file name with .lbl instead of .img) to `pdr.read()` it still needs to be able to find the other one in order to get the metadata to know how to properly read in your data.

This is the link for downloading the corresponding label file for the data you have above: https://pds-geosciences.wustl.edu/mro/mro-m-crism-6-ddr-v1/mrocr_1002/ddr/2009/2009_118/hrl00012522/hrl00012522_07_de183l_ddr1.lbl

Do note that some browsers will download the label files as a .txt (so they'll end up as .lbl.txt files--not what you want). If you right click and save as you can change the file extension by changing the name (just remove the .txt; leave the .lbl) and switching the file ending drop down in the bottom right hand corner to .* (All files) instead of .txt/.TXT.

Once you have that downloaded, just make sure it's in the same folder as your data file and use the same code you did to produce the error in this issue and you should be all good to go.  Feel free to reach out with any further issues you encounter. I did a lot of CRISM data work during my PhD so I'm well versed in its idiosyncrasies.

**Comment by justinbl** [comment]
Thanks, Sierra. I can work with ddr data now.

Best,
Binlong

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
