### ISSUE TITLE
Support for non-SRC MEX/HRSC images

### ISSUE THREAD

**Issue by msbentley** [MillionConcepts/pdr#55]
HRSC SRC (super resolution camera) images are already supported, but other image types are not:

> UserWarning: This product's IMAGE is not yet supported: 'Conventional' line pre[/suffixes](http://localhost:8888/suffixes) are not supported for non-BIL multiband images..

Having a quick look I guess this is because of the odd use of `BAND_STORAGE_TYPE` and `BANDS` for what is essentially a single-band image (probably coming from the similar way things are defined in VICAR?). In fact if I edit the attached PDS3 label to remove these two lines, pdr loads the image AOK.

An example image: https://archives.esac.esa.int/psa/ftp/MARS-EXPRESS/HRSC/MEX-M-HRSC-3-RDR-EXT9-V4.0/DATA/N998/HN998_0000_ND3.IMG

Alternatively, is there a simple way to modify the meta-data after read and have pdr use these updates, e.g. to remove the offending keywords from the meta-data dictionary?

Thanks for your help!

**Comment by Sierra-MC** [comment]
Hi Mark,

Just pushed a fix for this to `develop` commit [26ce78d](https://github.com/MillionConcepts/pdr/commit/26ce78d1af15b5d13a11c16b27a61ea1649eb58a). You were correct on the diagnosis, we had checks for single band images with claimed multiband properties in other areas of the codebase but were missing one for BIL interleaved images with line prefix/suffixes. Thanks for finding this and pointing out the oversight. The fix will be in our next release (which I'll put out in a couple days, we have a few other things to merge first otherwise I'd push you a new one now).

As for your alternative it has caused us to have a discussion and we are looking into adding a power user feature that will allow changes to the Metadata object to be propagated through to the loader (which will also probably be in the next release with this fix too). So thanks also for the suggestion; you're appreciated!

**Comment by msbentley** [comment]
Thanks @Sierra-MC for the speedy fix - we'll update when the next release is out! Yes, I can foresee a few cases where it may be useful to modify things on-the-fly, so thanks for considering that use also.

**Comment by Sierra-MC** [comment]
@msbentley the new release with these changes and the new metadata editing feature is out on `pip` and `conda`. See [release notes](https://github.com/MillionConcepts/pdr/releases/tag/v1.1.0) for example usage of the metadata change feature.
