### ISSUE TITLE
Reading an image with attached label instead reads detached label

### ISSUE THREAD

**Issue by msbentley** [MillionConcepts/pdr#56]
Mars Express HRSC images (unfortunately) comes with two versions in the data directory:
- `.IMG` (PDS3 image, attached label)
- `.LBL` + `.JP2` (JPG2000, detached label)

They share the same name, so that we have in one folder
```
HJ592_0000_S23.IMG
HJ592_0000_S23.JP2
HJ592_0000_S23.LBL
```
see for example:
http://archives.esac.esa.int/psa/ftp/MARS-EXPRESS/HRSC/MEX-M-HRSC-5-REFDR-MAPPROJECTED-V3.0/DATA/J592/

Currently if you point pdr to the `.IMG` file, it seems to pick up the `.LBL` with the same filename *before* checking for an attached label, so explitly trying to open e.g. `HJ592_0000_S23.IMG` actually opens `HJ592_0000_S23.LBL`.

I understand the situation here is a bit messy ;-) but it would be great if a future version could check first for the attached label, or similar?

**Comment by m-stclair** [comment]
We don't automatically prefer attached labels because there are many products that have attached PVL headers that *aren't* their "real" labels, but rather ancillary metadata etc. The diversity of file naming conventions means that `pdr`'s automatic label file/data file association is not guaranteed to work 100% of the time.

Fortunately, there are a couple of easy mechanisms for cases like this:

1. You can specify the label file by passing the `label_fn` argument to `pdr.read()`. This is also useful for cases in which a data file's filename stem does not match the filename stem of its detached label, or if the label file is elsewhere on the filesystem, etc.
2. In the specific case here -- you know that a data file has an attached label and you don't want to check for a detached label -- you can open it with `pdr.fastread(data_fn)`

(Note that `pdr.fastread(data_fn, *args, **kwargs)` is just an alias for `pdr.read(data_fn, *args, label_fn=data_fn, skip_existence_check=True, **kwargs)`. It can also improve performance when you are running a program that reads a large number of products, particularly on a slow filesystem.)

**Comment by msbentley** [comment]
Great, many thanks @m-stclair we'll go ahead using those hints!
