### ISSUE TITLE
Add support for line prefixes in tables

### ISSUE THREAD

**Issue by Sierra-MC** [MillionConcepts/pdr#62]
We currently do not support line prefixes. The known unsupported products affected by this issue include:

 - cassini_iss line_prefix_tables
 - gal_ssi redr
 - mex_hrsc rdr_hrsc
 - sl9_jupiter_impact gal_ssi

**Comment by m-stclair** [comment]
Fixed by d8a304b7daf7df823767b141a9373a190f987672. 

At this point, we have addressed most pre/suffix and axplane loading issues except for some of the extremely funky ISIS2 cases, so we can start considering how we might actually _return_ those "non-primary" data.  [I have opened a separate issue on this topic.](https://github.com/MillionConcepts/pdr/issues/74)
